from abc import ABC, abstractmethod

class Player(ABC):
    """
    Implements an Opponent to play Santorini against. Uses one of the various Agent implementations such as FS or
    MiniMax to generate moves.
    """

    def __init__(self, player_number: int):
        self.player_number = player_number

    @abstractmethod
    def getAction(self, game, action_type: ActionType) -> Action:
        """
        Execute an action. Chooses action generated by the policy Agent.
        :param game: GameState representation of the current game board. See class GameState
        """
        pass

    @abstractmethod
    def getPlayerPiece(self) -> str:
        pass

    def getPlayerNumber(self) -> int:
        return self.player_number



