from Game import SantoriniGame, ActionType, Action, Board, BoardLocation


class Player():
    """
    A vanilla Santorini player with the standard ruleset.
    """

    def __init__(self, player_number: int, player_piece: str, agent: "Agent"):
        self.player_number = player_number
        self.player_piece = player_piece
        self.agent = agent
    
    def getMoveActionDirections(self) -> tuple[str, ...]:
        return (
            "UP",
            "DOWN",
            "LEFT",
            "RIGHT",
            "UP_LEFT",
            "DOWN_LEFT",
            "UP_RIGHT",
            "DOWN_RIGHT",
        )
    
    def getBuildActionDirections(self) -> tuple[str, ...]:
        return self.getMoveActionDirections()
    
    def getTurnSequence(self) -> tuple[ActionType, ...]:
        return ("MOVE", "BUILD")
    
    def playTurn(self, game: SantoriniGame):
        for action_type in self.getTurnSequence():
            if self not in game.losers and not game.isGameOver():
                action = self.getAction(game, action_type)
                game.applyAction(action)
    
    def getAction(self, game: SantoriniGame, action_type: ActionType) -> Action:
        """
        Execute an action. Chooses action generated by the policy Agent.
        :param game: GameState representation of the current game board. See class GameState
        """
        if game.verbose:
            print(f"Player {self.getPlayerNumber()} is choosing a {action_type}...")

        return self.agent.getAction(game, self, action_type)

    def getPlayerPiece(self) -> str:
        return self.player_piece

    def getPlayerNumber(self) -> int:
        return self.player_number
    
    def isWinner(self, board: Board, current_position: BoardLocation) -> bool:
        # player wins if they reach height 3
        return current_position[2] == 3
    
    def isLoser(self, board: Board, current_position: BoardLocation) -> bool:
        # player loses if they have no valid actions remaining
        return not self.getAllValidMoveActions(board, current_position) or not self.getAllValidBuildActions(board, current_position)

    def getAllValidMoveActions(self, board: Board, current_position: BoardLocation) -> list[Action]:
        """
        """
        valid_actions: list[Action] = []

        for dir in self.getMoveActionDirections():
            new_position = self.getBoardPositionFromActionDirection(board, current_position, dir)
            if self.isValidMoveAction(board, current_position, new_position):
                valid_actions.append(Action(self, "MOVE", new_position))
        return valid_actions
    
    def getAllValidBuildActions(self, board: Board, current_position: BoardLocation) -> list[Action]:
        """
        Enumerates list of all valid build actions from current state

        :param board: GameState representation of the current game board. See class GameState
        :param position: [3x1] list of [y,x,z] coordinates representing current position
        :return: action_list: list of valid actions, where 'action' = {'move', 'build'} and 'dir' can be 'u', 'd', etc...
        """
        valid_actions: list[Action] = []

        for dir in self.getBuildActionDirections():
            build_location = self.getBoardPositionFromActionDirection(board, current_position, dir)
            if self.isValidBuildAction(board, build_location):
                valid_actions.append(Action(self, "BUILD", build_location))
        return valid_actions
    
    def getAllValidStartingActions(self, board: Board) -> list[Action]:
        """
        """
        valid_actions: list[Action] = []

        for i in range(len(board[:][0])):
            for j in range(len(board[0][:])):
                if not board[i][j].player:
                    valid_actions.append(Action(self, "CHOOSE_STARTNG_POSITION", (i, j, 0)))
        return valid_actions

    @staticmethod
    def isValidMoveAction(board: Board, start_pos: BoardLocation, end_pos: BoardLocation) -> bool:
        """

        """
        if end_pos[0] < 0 or end_pos[0] >= len(board[:][0]) or end_pos[1] < 0 or end_pos[1] >= len(board[0][:]):
            return False
        if board[end_pos[0]][end_pos[1]].player is None \
                and board[end_pos[0]][end_pos[1]].height <= start_pos[2] + 1 \
                and end_pos[0] >= 0 and end_pos[1] >= 0 and board[end_pos[0]][end_pos[1]].height <= 3:
            return True
        return False
    
    @staticmethod
    def isValidBuildAction(board: Board, build_pos: BoardLocation) -> bool:
        """
        """
        if build_pos[0] < 0 or build_pos[0] >= len(board[:][0]) or build_pos[1] < 0 or build_pos[1] >= len(board[0][:]):
            return False
        if build_pos[0] >= 0 and build_pos[1] >= 0 and board[build_pos[0]][build_pos[1]].height <= 3 \
                and board[build_pos[0]][build_pos[1]].player is None:
            return True
        return False
    
    @staticmethod
    def getBoardPositionFromActionDirection(board: Board, current_position: BoardLocation, action_direction: str) -> BoardLocation:
        """
        """

        x, y, z = current_position

        if "UP" in action_direction:
            x -= 1
        if "DOWN" in action_direction:
            x += 1
        if "RIGHT" in action_direction:
            y += 1
        if "LEFT" in action_direction:
            y -= 1

        if 0 <= x < len(board[:][0]) and 0 <= y < len(board[0][:]):
            z = board[x][y].height

        return (x, y, z)
    
    # @staticmethod 
    # def getNextPlayer(game: SantoriniGame, current_player: Player, current_action_type: ActionType) -> Player:
    #     if current_action_type == current_player.TurnSequence[-1]:
    #         return game.players[game.players.index(current_player) + 1 % len(game.players)]
    #     return current_player
    
    # @staticmethod
    # def getNextActionType(game: SantoriniGame, current_player: Player, current_action_type: ActionType) -> ActionType:
    #     if current_action_type == current_player.TurnSequence[-1]:
    #         return Player.getNextPlayer(game, current_player, current_action_type).TurnSequence[0]
    #     return current_player.TurnSequence[]


from abc import ABC, abstractmethod

class Agent(ABC):

    # agents may have state that we don't want to duplicate
    # for example, neural nets
    def __copy__(self):
        raise TypeError("This class cannot be copied.")
    
    def __deepcopy__(self, memo):
        raise TypeError("This class cannot be deep copied.")

    @abstractmethod
    def getAction(self, game: SantoriniGame, player: Player, action_type: ActionType) -> Action:
        pass


