from Game import SantoriniGame, ActionType, Action, Board, BoardLocation


class Player():
    """
    A vanilla Santorini player with the standard ruleset.
    """

    def __init__(self, player_number: int, player_piece: str, agent: "Agent"):
        self._player_number = player_number
        self._player_piece = player_piece
        self._agent = agent
    
    def __repr__(self) -> str:
        return f"<Player {self.getPlayerNumber()} ({self.getAgent().__class__.__name__})>"
    
    def getMoveActionDirections(self) -> tuple[str, ...]:
        return (
            "UP",
            "DOWN",
            "LEFT",
            "RIGHT",
            "UP_LEFT",
            "DOWN_LEFT",
            "UP_RIGHT",
            "DOWN_RIGHT",
        )

    def getPlayerPiece(self) -> str:
        return self._player_piece

    def getPlayerNumber(self) -> int:
        return self._player_number

    def getAgent(self) -> "Agent":
        return self._agent

    def getBuildActionDirections(self) -> tuple[str, ...]:
        return self.getMoveActionDirections()
    
    def getTurnSequence(self) -> tuple[ActionType, ...]:
        return ("MOVE", "BUILD")
        
    def getNextPlayer(self, players: list["Player"], action_type: ActionType) -> "Player":
        # TODO: figure out how to implement this for the case where a player can have repeating action types in a single turn
        if action_type == self.getTurnSequence()[-1]:
            # next player's turn
            return players[(players.index(self) + 1) % len(players)]
        # still this player's turn
        return self
    
    def getNextActionType(self, players: list["Player"], action_type: ActionType):
        # TODO: figure out how to implement this for the case where a player can have repeating action types in a single turn
        
        next_player = self.getNextPlayer(players, action_type)
        turn_sequence = next_player.getTurnSequence()
        
        if next_player is not self:
            return turn_sequence[0]
        return turn_sequence[turn_sequence.index(action_type) + 1]
    
    def getAction(self, game: SantoriniGame, action_type: ActionType) -> Action:
        """
        Execute an action. Chooses action generated by the policy Agent.
        """
        if game.verbose:
            print(f"Player {self.getPlayerNumber()} is choosing a {action_type}...")

        return self._agent.getAction(game, self, action_type)
    
    def playTurn(self, game: SantoriniGame):
        for action_type in self.getTurnSequence():
            if self not in game.losers and not game.isGameOver():
                action = self.getAction(game, action_type)
                game.applyAction(action)
    
    def isWinner(self, board: Board, current_position: BoardLocation) -> bool:
        # player wins if they reach height 3
        return current_position[2] == 3
    
    def isLoser(self, board: Board, current_position: BoardLocation) -> bool:
        # player loses if they have no valid actions remaining
        return not self._getValidMoveActions(board, current_position) or not self._getValidBuildActions(board, current_position)

    def getValidActions(self, board: Board, current_position: BoardLocation, action_type: ActionType) -> list[Action]:
        """
        """
        if action_type == "CHOOSE_STARTNG_POSITION":
            return self._getValidStartingActions(board)
        if action_type == "MOVE":
            return self._getValidMoveActions(board, current_position)
        if action_type == "BUILD":
            return self._getValidBuildActions(board, current_position)
        raise ValueError(action_type)
    
    def _getValidMoveActions(self, board: Board, current_position: BoardLocation) -> list[Action]:
        """
        """
        valid_actions: list[Action] = []

        for dir in self.getMoveActionDirections():
            new_position = self._getPositionFromActionDirection(board, current_position, dir)
            if self._isValidMoveAction(board, current_position, new_position):
                valid_actions.append(Action(self, current_position, "MOVE", dir, new_position))
        return valid_actions
    
    def _getValidBuildActions(self, board: Board, current_position: BoardLocation) -> list[Action]:
        """
        Enumerates list of all valid build actions from current state

        :param board: GameState representation of the current game board. See class GameState
        :param position: [3x1] list of [y,x,z] coordinates representing current position
        :return: action_list: list of valid actions, where 'action' = {'move', 'build'} and 'dir' can be 'u', 'd', etc...
        """
        valid_actions: list[Action] = []

        for dir in self.getBuildActionDirections():
            build_location = self._getPositionFromActionDirection(board, current_position, dir)
            if self._isValidBuildAction(board, build_location):
                valid_actions.append(Action(self, current_position, "BUILD", dir, build_location))
        return valid_actions
    
    def _getValidStartingActions(self, board: Board) -> list[Action]:
        """
        """
        valid_actions: list[Action] = []

        for i in range(len(board[:][0])):
            for j in range(len(board[0][:])):
                if not board[i][j].player:
                    valid_actions.append(Action(self, (i, j, 0), "CHOOSE_STARTNG_POSITION", "", (i, j, 0)))
        return valid_actions

    @staticmethod
    def _isValidMoveAction(board: Board, start_pos: BoardLocation, end_pos: BoardLocation) -> bool:
        """

        """
        if end_pos[0] < 0 or end_pos[0] >= len(board[:][0]) or end_pos[1] < 0 or end_pos[1] >= len(board[0][:]):
            return False
        if board[end_pos[0]][end_pos[1]].player is None \
                and board[end_pos[0]][end_pos[1]].height <= start_pos[2] + 1 \
                and end_pos[0] >= 0 and end_pos[1] >= 0 and board[end_pos[0]][end_pos[1]].height <= 3:
            return True
        return False
    
    @staticmethod
    def _isValidBuildAction(board: Board, build_pos: BoardLocation) -> bool:
        """
        """
        if build_pos[0] < 0 or build_pos[0] >= len(board[:][0]) or build_pos[1] < 0 or build_pos[1] >= len(board[0][:]):
            return False
        if build_pos[0] >= 0 and build_pos[1] >= 0 and board[build_pos[0]][build_pos[1]].height <= 3 \
                and board[build_pos[0]][build_pos[1]].player is None:
            return True
        return False
    
    @staticmethod
    def _getPositionFromActionDirection(board: Board, current_position: BoardLocation, action_direction: str) -> BoardLocation:
        """
        """
        row, col, height = current_position

        if "UP" in action_direction:
            row -= 1
        if "DOWN" in action_direction:
            row += 1
        if "RIGHT" in action_direction:
            col += 1
        if "LEFT" in action_direction:
            col -= 1

        if 0 <= row < len(board[:][0]) and 0 <= col < len(board[0][:]):
            height = board[row][col].height

        return (row, col, height)
    

from abc import ABC, abstractmethod

class Agent(ABC):

    # agents may have state that we don't want to duplicate
    # for example, neural nets
    def __copy__(self):
        raise TypeError("This class cannot be copied.")
    
    def __deepcopy__(self, memo):
        raise TypeError("This class cannot be deep copied.")

    @abstractmethod
    def getAction(self, game: SantoriniGame, player: Player, action_type: ActionType) -> Action:
        pass


